### ISSUE TITLE
Annotation Update Postman Test Fail

### ISSUE THREAD

**Issue by tadhatch** [entagen/data-fusion-performance-testing#7]
**Top of the ticket kept up to date. No need to go through comments.**

### Location

qa.datafusion.thomsonreuters.com

### Steps

Every 12 hours the postman test is run for annotation update.

### Expected

Test passes, and QA is ok.

### Actual

401 Errors for valid credentials:

```
curl -L -u "user:pass" --request POST   --url 'http://qa.datafusion.thomsonreuters.com/datafusion/api/annotation?subject=%3Chttp%3A%2F%2Ffeed.thomsonreuters.com%2F1-34414270192%3E&object=%3Chttp%3A%2F%2Ffeed.thomsonreuters.com%2F1-4297784683%3E&predicate=%3Chttp%3A%2F%2Ffeed.thomsonreuters.com%2Fproperty%2Flinks%2FisOfficerOf%3E&score=1&activeRange=-2208988800000%201350604800000'   --header 'Content-Type: application/json'   --data '{ "officer'\''s permid": {"value": "34414270192", "type": "NUMBER"}, "title": {"value": "* to 2012-10-19 Executive Officer", "type": "TEXT"}, "annotation test": {"value": "{{annotationTestTimestamp}}", "type":"TEXT"} }'
```
Returns:
```
{"timestamp":1527009369954,"status":401,"error":"Unauthorized","message":"No message available","path":"/datafusion/api/annotation"}
```

### Impact/Visibility

Low - Postman test. Instance appears fine
Low - QA instance only

**Comment by akio-outori** [comment]
@tadhatch Do we know what was causing the internal server error postman reported here?  Curious how that's different than our 401s.

**Comment by tadhatch** [comment]
It looks like the command in postman isn't using the `-L` flag - so it's not following redirects. Also, it's not using the `-u <login:info>` either.

**Comment by nnguyen** [comment]
If it is 500, then it could be https://github.com/entagen/data-fusion/issues/7428

**Comment by tadhatch** [comment]
Initially the postman is returning a 302. Then in the shell running the curl command we get a 401.

**Comment by obildtsen** [comment]
Determined to happen because the annotations don't exist.
